apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yydncuav6-nodejs 
  janus-idp.io/tekton: yydncuav6-nodejs
  backstage.io/kubernetes-id: yydncuav6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yydncuav6-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  