apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yydncuav6-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/yydncuav6-nodejs-gitops